//visibility
export const SET_VISIBILITY = 'SET_VISIBILITY'
//fetch
// fetch list
export const FETCH_BLACKLIST = 'FETCH_BLACKLIST'
export const FETCH_CLASSLIST = 'FETCH_CLASSLIST'
export const FETCH_WHITELIST = 'FETCH_WHITELIST'
export const FETCH_SENSITIVEWORDSLIST = 'FETCH_SENSITIVEWORDSLIST'
export const FETCH_SHIELDRECORD = 'FETCH_SHIELDRECORD'
export const FETCH_REQUESTRECORD = 'FETCH_REQUESTRECORD'

// receive list
export const RECEIVE_BLACKLIST = 'RECEIVE_BLACKLIST'
export const RECEIVE_CLASSLIST = 'RECEIVE_CLASSLIST'
export const RECEIVE_WHITELIST = 'RECEIVE_WHITELIST'
export const RECEIVE_SENSITIVEWORDS_LIST = 'RECEIVE_SENSITIVEWORDSLIST'
export const RECEIVE_REQUESTRECORD = 'RECEIVE_REQUESTRECORD'
export const RECEIVE_SHIELDRECORD = 'RECEIVE_SHIELDRECORD'

//modify data
export const RECEIVE_DEL_ONE_WHITELIST = 'RECEIVE_DEL_ONE_WHITELIST'
export const RECEIVE_DEL_ONE_BLACKLIST = 'RECEIVE_DEL_ONE_BLACKLIST'
export const RECEIVE_DEL_ONE_SENSITIVEWORDSLIST = 'RECEIVE_DEL_ONE_SENSITIVEWORDSLIST'
export const RECEIVE_DEL_ONE_REQUESTRECORD = 'RECEIVE_DEL_ONE_REQUESTRECORD'
export const RECEIVE_DEL_ONE_SHIELDRECORD = 'RECEIVE_DEL_ONE_SHIELDRECORD'
export const RECEIVE_DEL_ALL_REQUESTRECORD = 'RECEIVE_DEL_ALL_REQUESTLIST'
export const RECEIVE_DEL_ALL_SHIELDRECORD = 'RECEIVE_DEL_ALL_SHIELDLIST'
export const RECEIVE_ADD_ONE_WHITELIST = 'RECEIVE_ADD_ONE_WHHITELIST'
export const RECEIVE_ADD_ONE_BLACKLIST = 'RECEIVE_ADD_ONE_BLACKLIST'
export const RECEIVE_ADD_ONE_SENSITIVEWORDSLIST = 'RECEIVE_ADD_ONE_SHIELDLIST'
export const RECEIVE_TOGGLE_CLASSLIST = 'RECEIVE_TOGGLE_CLASSLIST'
