//visibility
export const SET_VISIBILITY = 'SET_VISIBILITY'
//fetch
export const FETCH_BLACKLIST = 'FETCH_BLACKLIST'
export const FETCH_WHITELIST = 'FETCH_WHITELIST'
export const FETCH_SHIELDLIST = 'FETCH_SHIELDLIST'
export const FETCH_REQUESTLIST = 'FETCH_REQUESTLIST'
export const RECEIVE_BLACKLIST = 'RECEIVE_BLACKLIST'
export const RECEIVE_WHITELIST = 'RECEIVE_WHITELIST'
export const RECEIVE_REQUESTLIST = 'RECEIVE_REQUESTLIST'
export const RECEIVE_SHIELDLIST = 'RECEIVE_SHIELDLIST'
